name: screen_post
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  # equatable
  equatable: ^2.0.5
  # state manager
  flutter_bloc: ^8.1.5
  # path
  path_provider: ^2.1.3
  # box
  gap: ^3.0.1
  # router
  go_router: ^14.0.1
  # svg
  flutter_svg: any
  # url launchers
  url_launcher: ^6.2.6
  # package info
  package_info_plus: ^8.0.0
  # cached network image
  cached_network_image: ^3.3.1
  # modal_bottom_sheet
  modal_bottom_sheet: ^3.0.0
  # top snackbar
  top_snackbar_flutter: ^3.1.0
  intl: ^0.19.0

  flutter_localization: ^0.2.0
  flutter_chat_bubble: ^2.0.2
  swipe_to: ^1.0.6
  encrypt: ^5.0.0
  flutter_secure_storage: ^7.0.0
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/locale/
    - assets/images/
    - assets/images/gifs/
    - assets/icons/
    - assets/icons/telegram/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 200
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 500
        - asset: assets/fonts/Lato-Black.ttf
          weight: 600


